plugins {
    id 'com.android.application'
}

android {
    namespace 'com.vsbox.launcher'
    compileSdk 34

    defaultConfig {
        applicationId "com.vsbox.launcher"
        minSdk 24
        targetSdk 34
        versionCode 3
        versionName "1.2"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

configurations.all {
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
    implementation 'dev.rikka.shizuku:aidl:13.1.5'
}
